export const INDUSTRY_FIELDS = [
  "Agriculture",
  "Farming",
  "Food & Beverages",
  "Textiles",
  "Apparel",
  "Leather Goods",
  "Manufacturing",
  "Electronics",
  "Electrical Equipment",
  "Pharmaceuticals",
  "Chemicals",
  "Plastics",
  "Packaging",
  "Retail",
  "Wholesale",
  "E-commerce",
  "Information Technology",
  "Software Development",
  "SaaS",
  "Web Development",
  "Mobile App Development",
  "Cybersecurity",
  "Cloud Services",
  "AI & Data Analytics",
  "Professional Services",
  "Legal Services",
  "Accounting",
  "Consulting",
  "HR & Staffing",
  "Digital Marketing",
  "Graphic Design",
  "Healthcare",
  "Hospitals",
  "Clinics",
  "Diagnostics",
  "Pharmacy",
  "Medical Devices",
  "Education",
  "Schools",
  "Colleges",
  "Coaching Institutes",
  "Online Training",
  "Transport",
  "Logistics",
  "Courier Services",
  "Warehousing",
  "Travel & Tourism",
  "Taxi & Cab Services",
  "Real Estate",
  "Construction",
  "Architecture",
  "Interior Design",
  "Hospitality",
  "Restaurants",
  "Cafés",
  "Hotels",
  "Catering",
  "Finance",
  "Banking",
  "Insurance",
  "Investments",
  "Media",
  "Advertising",
  "Film & Video",
  "Events",
  "Gaming",
  "Beauty",
  "Cosmetics",
  "Jewelry",
  "Lifestyle",
  "Footwear",
  "Automotive",
  "Auto Repair",
  "Auto Parts",
  "EV Services",
  "Home Services",
  "Plumbing",
  "Electrical",
  "Cleaning",
  "Pest Control",
  "Printing",
  "Publishing",
  "Renewable Energy",
  "Solar",
  "Waste Management",
  "Water Treatment",
  "Sports",
  "Fitness",
  "Recreation",
] as const;

export type IndustryField = typeof INDUSTRY_FIELDS[number];
